auth_token: tmpsecret

database:
  connection_string: postrgres://local:supersecurepassword@localhost:5432/lor_e
  max_connections: 5

github_api:
  auth_token: ""

huggingface_api:
  auth_token: ""

message_config:
  pre: "Hello!\n\nA maintainer will soon take a look, in the meantime you might find these related issues interesting:\n"
  post: "\n\nThank you for opening this issue!"

model_api:
  auth_token: ""
  url: ""

model:
  id: NovaSearch/stella_en_1.5B_v5
  revision: main
  embeddings_size: 1024
  max_input_size: 131072

server:
  ip: 0.0.0.0
  metrics_port: 4243
  port: 4242
